# Abrindo os bancos de dados de features e padronizando 

Cópia para abrir e trabalhar em testes rápidos nos arquivos de features

In [2]:
import numpy as np
import pandas as pd
import networkx as nx
import sys, os, h5py
sys.path.append(os.path.abspath('../EMOGI'))
import gcnPreprocessing
import gcnIO
import matplotlib.pyplot as plt
%matplotlib inline

## Multinet

In [274]:
sorted_column_MULTINET_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/MULTINET_features_padrao.tsv', sep= '\t', index_col='Unnamed: 0')

MULTINET_features = sorted_column_MULTINET_features.rename(columns={"Unnamed: 0.1": "gene"})

MULTINET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,A2BP1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
14394,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.000000,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [275]:
lista_MULTINET = MULTINET_features[['gene']]

lista_MULTINET

         gene
0        A1CF
1       A2BP1
2         A2M
3        AAAS
4        AACS
...       ...
14393    ZXDC
14394  ZYG11B
14395     ZYX
14396   ZZEF1
14397    ZZZ3

[14398 rows x 1 columns]

In [276]:
lista_MULTINET.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_MULTINET.tsv', sep='\t', header=False, index=False)

In [277]:
MULTINET_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_MULTINET_trad2.csv', header=1)

MULTINET_features_trad

,Input,Match type,Approved symbol,Approved name,HGNC ID,Location
0,A1CF,Approved symbol,A1CF,APOBEC1 complementation factor,HGNC:24086,10q11.23
1,A2BP1,Alias symbol,RBFOX1,RNA binding fox-1 homolog 1,HGNC:18222,16p13.3
2,A2M,Approved symbol,A2M,alpha-2-macroglobulin,HGNC:7,12p13.31
3,AAAS,Approved symbol,AAAS,aladin WD repeat nucleoporin,HGNC:13666,12q13.13
4,AACS,Approved symbol,AACS,acetoacetyl-CoA synthetase,HGNC:21298,12q24.31
...,...,...,...,...,...,...
14930,ZXDC,Approved symbol,ZXDC,ZXD family zinc finger C,HGNC:28160,3q21.3
14931,ZYG11B,Approved symbol,ZYG11B,"zyg-11 family member B, cell cycle regulator",HGNC:25820,1p32.3
14932,ZYX,Approved symbol,ZYX,zyxin,HGNC:13200,7q34
14933,ZZEF1,Approved symbol,ZZEF1,zinc finger ZZ-type and EF-hand domain contain...,HGNC:29027,17p13.2
14934,ZZZ3,Approved symbol,ZZZ3,zinc finger ZZ-type containing 3,HGNC:24523,1p31.1

In [278]:
MULTINET_features_trad2 = MULTINET_features_trad.drop(columns=['Approved name', 'Location'])

MULTINET_features_trad2

        Input       Match type Approved symbol     HGNC ID
0        A1CF  Approved symbol            A1CF  HGNC:24086
1       A2BP1     Alias symbol          RBFOX1  HGNC:18222
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4        AACS  Approved symbol            AACS  HGNC:21298
...       ...              ...             ...         ...
14930    ZXDC  Approved symbol            ZXDC  HGNC:28160
14931  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
14932     ZYX  Approved symbol             ZYX  HGNC:13200
14933   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
14934    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[14935 rows x 4 columns]

In [279]:
MULTINET_features_trad2['Match type'].value_counts()

Approved symbol    12439
Previous symbol     1635
Alias symbol         582
Unmatched            269
Entry withdrawn       10
Name: Match type, dtype: int64

In [280]:
# Solução 1
# Remover as duplicadas da coluna input, idealmente ficaria com a mesma quantidade de genes da lista enviada para o site, 
# a partir daí se faria a tradução de todos para os correspondentes da coluna approved

MULTINET_features_solucao1 = MULTINET_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

MULTINET_features_solucao1

        Input       Match type Approved symbol     HGNC ID
0        A1CF  Approved symbol            A1CF  HGNC:24086
1       A2BP1     Alias symbol          RBFOX1  HGNC:18222
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4        AACS  Approved symbol            AACS  HGNC:21298
...       ...              ...             ...         ...
14930    ZXDC  Approved symbol            ZXDC  HGNC:28160
14931  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
14932     ZYX  Approved symbol             ZYX  HGNC:13200
14933   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
14934    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[14398 rows x 4 columns]

In [281]:
MULTINET_features_solucao1['Match type'].value_counts()

Approved symbol    12439
Previous symbol     1547
Unmatched            269
Alias symbol         133
Entry withdrawn       10
Name: Match type, dtype: int64

In [282]:
# Salvando a lista final de traduções 

MULTINET_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_MULTINET_final2.tsv', sep='\t')

In [ ]:
# Para fazer a leitura depois 

#MULTINET_features_6 = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_MULTINET_final.tsv', sep='\t', index_col='Unnamed: 0')

#MULTINET_features_6

## CPDB

In [283]:
sorted_column_CPDB_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/CPDB_features_padrao.tsv', sep='\t', index_col='Unnamed: 0')

CPDB_features = sorted_column_CPDB_features.rename(columns={"Unnamed: 0.1": "gene"})

CPDB_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,STIM1,0.000000,0.000000,0.449339,0.000000,0.0,0.428947,0.000000,0.000000,0.000000,...,0.000000,0.040940,0.000000,0.060833,0.000000,0.000000,0.000000,0.012993,0.003601,0.007459
1,TRPC1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040655,0.024799,0.060202,0.054278,0.022758,0.000000,0.000000,0.000000,0.007545
2,NOS1,0.000000,0.000000,0.000000,0.000000,0.0,0.165789,0.000000,0.000000,0.000000,...,0.063345,0.080900,0.048884,0.038974,0.103072,0.022690,0.055677,0.048721,0.000000,0.028677
3,ATP2B4,0.272727,0.000000,0.000000,0.000000,0.0,0.000000,0.148387,0.000000,0.000000,...,0.038215,0.000000,0.074138,0.040063,0.054143,0.045420,0.053870,0.025206,0.007193,0.014863
4,ABCC9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.012769,0.040659,0.024758,0.058909,0.000000,0.045414,0.055910,0.187905,0.010787,0.029335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,GPR153,0.000000,0.000000,0.176211,0.000000,0.0,0.250000,0.212903,0.271357,0.597786,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007677
13623,HDC,0.000000,0.000000,0.308370,0.000000,0.0,0.000000,0.000000,0.175879,0.000000,...,0.000000,0.000000,0.000000,0.040862,0.000000,0.022764,0.000000,0.026045,0.003603,0.007667
13624,CSMD1,0.920455,0.708492,0.000000,0.582822,0.0,0.000000,0.000000,0.000000,0.000000,...,0.062828,0.158012,0.169735,0.332902,0.248689,0.157486,0.108880,0.346369,0.010780,0.046940
13625,BHLHE22,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040962,0.025052,0.000000,0.000000,0.000000,0.000000,0.025961,0.000000,0.003847
13626,PROKR1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.040201,0.000000,...,0.000000,0.000000,0.025006,0.061207,0.000000,0.022764,0.000000,0.038959,0.000000,0.015383

In [284]:
lista_CPDB = CPDB_features[['gene']]

lista_CPDB

          gene
0        STIM1
1        TRPC1
2         NOS1
3       ATP2B4
4        ABCC9
...        ...
13622   GPR153
13623      HDC
13624    CSMD1
13625  BHLHE22
13626   PROKR1

[13627 rows x 1 columns]

In [27]:
lista_CPDB.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_CPDB.tsv', sep='\t', header=False, index=False)

In [285]:
CPDB_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_CPDB_trad2.csv', header=1)

CPDB_features_trad2 = CPDB_features_trad.drop(columns=['Approved name', 'Location'])

CPDB_features_trad2

         Input       Match type Approved symbol     HGNC ID
0        STIM1  Approved symbol           STIM1  HGNC:11386
1        TRPC1  Approved symbol           TRPC1  HGNC:12333
2         NOS1  Approved symbol            NOS1   HGNC:7872
3         NOS1     Alias symbol          NANOS1  HGNC:23044
4       ATP2B4  Approved symbol          ATP2B4    HGNC:817
...        ...              ...             ...         ...
14153      HDC  Approved symbol             HDC   HGNC:4855
14154      HDC     Alias symbol            HECA  HGNC:21041
14155    CSMD1  Approved symbol           CSMD1  HGNC:14026
14156  BHLHE22  Approved symbol         BHLHE22  HGNC:11963
14157   PROKR1  Approved symbol          PROKR1   HGNC:4524

[14158 rows x 4 columns]

In [286]:
CPDB_features_trad2['Match type'].value_counts()

Approved symbol    13428
Alias symbol         446
Previous symbol      282
Entry withdrawn        2
Name: Match type, dtype: int64

In [287]:
CPDB_features_solucao1 = CPDB_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

CPDB_features_solucao1

         Input       Match type Approved symbol     HGNC ID
0        STIM1  Approved symbol           STIM1  HGNC:11386
1        TRPC1  Approved symbol           TRPC1  HGNC:12333
2         NOS1  Approved symbol            NOS1   HGNC:7872
4       ATP2B4  Approved symbol          ATP2B4    HGNC:817
5        ABCC9  Approved symbol           ABCC9     HGNC:60
...        ...              ...             ...         ...
14152   GPR153  Approved symbol          GPR153  HGNC:23618
14153      HDC  Approved symbol             HDC   HGNC:4855
14155    CSMD1  Approved symbol           CSMD1  HGNC:14026
14156  BHLHE22  Approved symbol         BHLHE22  HGNC:11963
14157   PROKR1  Approved symbol          PROKR1   HGNC:4524

[13627 rows x 4 columns]

In [288]:
CPDB_features_solucao1['Match type'].value_counts()

Approved symbol    13428
Previous symbol      195
Entry withdrawn        2
Alias symbol           2
Name: Match type, dtype: int64

In [289]:
# Salvando a lista final de traduções 

CPDB_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_CPDB_final2.tsv', sep='\t')

## IREF

In [290]:
sorted_column_IREF_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/IREF_features_padrao.tsv', sep='\t', index_col='Unnamed: 0')

IREF_features = sorted_column_IREF_features.rename(columns={"Unnamed: 0.1": "gene"})

IREF_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,DTX3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.025035,0.040857,0.000000,0.000000,0.0,0.012973,0.000000,0.000000
1,UBE2D4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022751,0.0,0.000000,0.000000,0.003881
2,PROP1,0.0,0.0,0.0,0.0,0.0,0.000000,0.713978,0.241206,0.0,...,0.000000,0.000000,0.000000,0.020519,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,MAGEA11,0.0,0.0,0.0,0.0,0.0,0.000000,0.079570,0.000000,0.0,...,0.000000,0.000000,0.000000,0.081227,0.000000,0.000000,0.0,0.038889,0.003603,0.011579
4,TRIM39,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.040836,0.000000,0.020380,0.054052,0.000000,0.0,0.012212,0.003598,0.003753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17008,GSTT2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17009,KCNK17,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.012835,0.000000,0.000000,0.040468,0.000000,0.022770,0.0,0.000000,0.000000,0.003856
17010,TGM6,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.025661,0.081913,0.000000,0.000000,0.054257,0.045526,0.0,0.026077,0.000000,0.019106
17011,IGSF11,0.0,0.0,0.0,0.0,0.0,0.000000,0.346237,0.000000,0.0,...,0.012793,0.000000,0.024650,0.039651,0.000000,0.022722,0.0,0.012370,0.000000,0.003582
17012,TBX3,0.0,0.0,0.0,0.0,0.0,0.165789,0.000000,0.000000,0.0,...,0.012827,0.040908,0.024975,0.080053,0.000000,0.091010,0.0,0.050628,0.000000,0.015128

In [291]:
lista_IREF = IREF_features[['gene']]

lista_IREF

          gene
0         DTX3
1       UBE2D4
2        PROP1
3      MAGEA11
4       TRIM39
...        ...
17008    GSTT2
17009   KCNK17
17010     TGM6
17011   IGSF11
17012     TBX3

[17013 rows x 1 columns]

In [36]:
lista_IREF.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF.tsv', sep='\t', header=False, index=False)

In [292]:
IREF_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_trad2.csv', header=1)

IREF_features_trad2 = IREF_features_trad.drop(columns=['Approved name', 'Location'])

IREF_features_trad2

         Input       Match type Approved symbol     HGNC ID
0         DTX3  Approved symbol            DTX3  HGNC:24457
1       UBE2D4  Approved symbol          UBE2D4  HGNC:21647
2        PROP1  Approved symbol           PROP1   HGNC:9455
3      MAGEA11  Approved symbol         MAGEA11   HGNC:6798
4       TRIM39  Approved symbol          TRIM39  HGNC:10065
...        ...              ...             ...         ...
17606    GSTT2  Approved symbol           GSTT2   HGNC:4642
17607   KCNK17  Approved symbol          KCNK17  HGNC:14465
17608     TGM6  Approved symbol            TGM6  HGNC:16255
17609   IGSF11  Approved symbol          IGSF11  HGNC:16669
17610     TBX3  Approved symbol            TBX3  HGNC:11602

[17611 rows x 4 columns]

In [293]:
IREF_features_trad2['Match type'].value_counts()

Approved symbol    16835
Alias symbol         516
Previous symbol      221
Unmatched             33
Entry withdrawn        6
Name: Match type, dtype: int64

In [294]:
IREF_features_solucao1 = IREF_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

IREF_features_solucao1

         Input       Match type Approved symbol     HGNC ID
0         DTX3  Approved symbol            DTX3  HGNC:24457
1       UBE2D4  Approved symbol          UBE2D4  HGNC:21647
2        PROP1  Approved symbol           PROP1   HGNC:9455
3      MAGEA11  Approved symbol         MAGEA11   HGNC:6798
4       TRIM39  Approved symbol          TRIM39  HGNC:10065
...        ...              ...             ...         ...
17606    GSTT2  Approved symbol           GSTT2   HGNC:4642
17607   KCNK17  Approved symbol          KCNK17  HGNC:14465
17608     TGM6  Approved symbol            TGM6  HGNC:16255
17609   IGSF11  Approved symbol          IGSF11  HGNC:16669
17610     TBX3  Approved symbol            TBX3  HGNC:11602

[17013 rows x 4 columns]

In [295]:
IREF_features_solucao1['Match type'].value_counts()

Approved symbol    16835
Previous symbol      123
Unmatched             33
Alias symbol          16
Entry withdrawn        6
Name: Match type, dtype: int64

In [296]:
# Salvando a lista final de traduções 

IREF_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_final2.tsv', sep='\t')

## PCNET

In [2]:
sorted_column_PCNET_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/PCNET_features_padrao.tsv', sep='\t', index_col='Unnamed: 0')

PCNET_features = sorted_column_PCNET_features.rename(columns={"Unnamed: 0.1": "gene"})

PCNET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,UBE2Q1,0.0,0.000000,0.696035,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.012837,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012896,0.000000,0.011571
1,RNF14,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.241206,0.000000,...,0.025470,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012068,0.007107,0.007325
2,UBE2Q2,0.0,0.000000,0.334802,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013017,0.003560,0.003769
3,TMCO1,0.0,0.000000,0.000000,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.003732
4,UBAC1,0.0,0.376426,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.439114,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013057,0.000000,0.011592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19776,BAGE4,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19777,FAM181B,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.061346,0.0,0.0,0.00000,0.013027,0.000000,0.000000
19778,IGFL3,0.0,0.000000,0.167401,0.0,0.000000,0.0,0.000000,0.095477,0.000000,...,0.000000,0.081971,0.0,0.000000,0.0,0.0,0.02843,0.013023,0.000000,0.000000
19779,BAT4,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19780,TPT1P8,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000

In [146]:
testedupli = PCNET_features['gene'].str.lower()

testedupli

0         ube2q1
1          rnf14
2         ube2q2
3          tmco1
4          ubac1
          ...
19776      bage4
19777    fam181b
19778      igfl3
19779       bat4
19780     tpt1p8
Name: gene, Length: 19781, dtype: object

In [147]:
testedupli.value_counts()

c8orf4       2
c19orf12     2
sumo1        1
eva1b        1
eva1c        1
            ..
hla-f-as1    1
kctd2        1
myo6         1
uts2d        1
riok1        1
Name: gene, Length: 19779, dtype: int64

In [12]:
print(PCNET_features.loc[PCNET_features['gene'] == 'C19ORF12'])

           gene  CNA: BLCA  CNA: BRCA  CNA: CESC  CNA: COAD  CNA: ESCA  \
18982  C19ORF12        0.0        0.0        0.0        0.0        0.0

       CNA: HNSC  CNA: KIRC  CNA: KIRP  CNA: LIHC  ...  MF: KIRC  MF: KIRP  \
18982        0.0        0.0        0.0        0.0  ...       0.0       0.0

       MF: LIHC  MF: LUAD  MF: LUSC  MF: PRAD  MF: READ  MF: STAD  MF: THCA  \
18982       0.0       0.0       0.0       0.0       0.0       0.0       0.0

       MF: UCEC
18982       0.0

[1 rows x 65 columns]

In [177]:
PCNET_features.drop([14942,15332], axis=0, inplace=True)


#PCNET_features3 = PCNET_features.drop(15332, 14942)

In [178]:
lista_PCNET = PCNET_features[['gene']]

lista_PCNET

          gene
0       UBE2Q1
1        RNF14
2       UBE2Q2
3        TMCO1
4        UBAC1
...        ...
19776    BAGE4
19777  FAM181B
19778    IGFL3
19779     BAT4
19780   TPT1P8

[19779 rows x 1 columns]

In [183]:
lista_PCNET.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_PCNET2.tsv', sep='\t', header=False, index=False)

In [13]:
PCNET_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_PCNET_trad2.csv', header=1)

PCNET_features_trad2 = PCNET_features_trad.drop(columns=['Approved name', 'Location'])

PCNET_features_trad2

         Input       Match type Approved symbol     HGNC ID
0       UBE2Q1  Approved symbol          UBE2Q1  HGNC:15698
1        RNF14  Approved symbol           RNF14  HGNC:10058
2       UBE2Q2  Approved symbol          UBE2Q2  HGNC:19248
3        TMCO1  Approved symbol           TMCO1  HGNC:18188
4        UBAC1  Approved symbol           UBAC1  HGNC:30221
...        ...              ...             ...         ...
20421    BAGE4  Approved symbol           BAGE4  HGNC:15730
20422  FAM181B  Approved symbol         FAM181B  HGNC:28512
20423    IGFL3  Approved symbol           IGFL3  HGNC:32930
20424     BAT4  Previous symbol          GPANK1  HGNC:13920
20425   TPT1P8  Approved symbol          TPT1P8  HGNC:24088

[20426 rows x 4 columns]

In [18]:
print(PCNET_features_trad2.loc[PCNET_features_trad2['Input'] == 'C19ORF12'])

          Input       Match type Approved symbol     HGNC ID
19621  C19ORF12  Approved symbol        C19orf12  HGNC:25443

In [185]:
PCNET_features_trad2['Match type'].value_counts()

Approved symbol    18525
Previous symbol     1152
Alias symbol         569
Unmatched            169
Entry withdrawn       11
Name: Match type, dtype: int64

In [186]:
PCNET_features_solucao1 = PCNET_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

PCNET_features_solucao1

         Input       Match type Approved symbol     HGNC ID
0       UBE2Q1  Approved symbol          UBE2Q1  HGNC:15698
1        RNF14  Approved symbol           RNF14  HGNC:10058
2       UBE2Q2  Approved symbol          UBE2Q2  HGNC:19248
3        TMCO1  Approved symbol           TMCO1  HGNC:18188
4        UBAC1  Approved symbol           UBAC1  HGNC:30221
...        ...              ...             ...         ...
20421    BAGE4  Approved symbol           BAGE4  HGNC:15730
20422  FAM181B  Approved symbol         FAM181B  HGNC:28512
20423    IGFL3  Approved symbol           IGFL3  HGNC:32930
20424     BAT4  Previous symbol          GPANK1  HGNC:13920
20425   TPT1P8  Approved symbol          TPT1P8  HGNC:24088

[19779 rows x 4 columns]

In [211]:
print(PCNET_features_solucao1.loc[PCNET_features_solucao1['Input'] == 'FAM71C'])

       Input       Match type Approved symbol     HGNC ID
9415  FAM71C  Previous symbol          GARIN6  HGNC:28594

In [188]:
PCNET_features_solucao1['Match type'].value_counts()

Approved symbol    18525
Previous symbol     1035
Unmatched            169
Alias symbol          39
Entry withdrawn       11
Name: Match type, dtype: int64

In [189]:
# Salvando a lista final de traduções 

PCNET_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_PCNET_final2.tsv', sep='\t')

## STRINGdb

In [297]:
sorted_column_STRINGdb_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/STRINGdb_features_padrao.tsv', sep='\t', index_col='Unnamed: 0')

STRINGdb_features = sorted_column_STRINGdb_features.rename(columns={"Unnamed: 0.1": "gene"})

STRINGdb_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,ARF5,0.000000,0.0,0.264317,0.0,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.000000,0.040985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011607
1,SPTBN2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012766,0.081138,0.048677,0.039826,0.053086,0.021047,0.025923,0.035777,0.007194,0.060659
2,KIF22,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012803,0.000000,0.000000,0.020363,0.000000,0.022747,0.000000,0.000000,0.000000,0.000000
3,DCTN6,0.954545,0.0,0.000000,0.0,0.517241,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013015,0.000000,0.003847
4,BET1,0.000000,0.0,0.000000,0.0,0.786207,0.444737,0.000000,0.000000,0.000000,...,0.000000,0.040930,0.050092,0.000000,0.000000,0.022755,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174,MFSD11,0.734848,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.081267,0.024685,0.000000,0.053600,0.000000,0.000000,0.013008,0.000000,0.007231
13175,SLCO1C1,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.038355,0.040815,0.024792,0.039038,0.162867,0.045482,0.000000,0.051008,0.000000,0.014983
13176,SLC16A2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012828,0.000000,0.000000,0.000000,0.054732,0.045522,0.028346,0.000000,0.000000,0.023163
13177,RNASE12,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013037,0.000000,0.000000
13178,RNASE11,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012824,0.000000,0.000000,0.000000,0.109436,0.000000,0.000000,0.012947,0.000000,0.007638

In [298]:
lista_STRINGdb = STRINGdb_features[['gene']]

lista_STRINGdb

          gene
0         ARF5
1       SPTBN2
2        KIF22
3        DCTN6
4         BET1
...        ...
13174   MFSD11
13175  SLCO1C1
13176  SLC16A2
13177  RNASE12
13178  RNASE11

[13179 rows x 1 columns]

In [52]:
lista_STRINGdb.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_STRINGdb.tsv', sep='\t', header=False, index=False)

In [299]:
STRINGdb_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_STRINGdb_trad2.csv', header=1)

STRINGdb_features_trad2 = STRINGdb_features_trad.drop(columns=['Approved name', 'Location'])

STRINGdb_features_trad2

         Input       Match type Approved symbol     HGNC ID
0         ARF5  Approved symbol            ARF5    HGNC:658
1       SPTBN2  Approved symbol          SPTBN2  HGNC:11276
2        KIF22  Approved symbol           KIF22   HGNC:6391
3        DCTN6  Approved symbol           DCTN6  HGNC:16964
4         BET1  Approved symbol            BET1  HGNC:14562
...        ...              ...             ...         ...
13700   MFSD11  Approved symbol          MFSD11  HGNC:25458
13701  SLCO1C1  Approved symbol         SLCO1C1  HGNC:13819
13702  SLC16A2  Approved symbol         SLC16A2  HGNC:10923
13703  RNASE12  Approved symbol         RNASE12  HGNC:24211
13704  RNASE11  Approved symbol         RNASE11  HGNC:19269

[13705 rows x 4 columns]

In [300]:
STRINGdb_features_trad2['Match type'].value_counts()

Approved symbol    13035
Alias symbol         459
Previous symbol      149
Unmatched             58
Entry withdrawn        4
Name: Match type, dtype: int64

In [301]:
STRINGdb_features_solucao1 = STRINGdb_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

STRINGdb_features_solucao1

         Input       Match type Approved symbol     HGNC ID
0         ARF5  Approved symbol            ARF5    HGNC:658
1       SPTBN2  Approved symbol          SPTBN2  HGNC:11276
2        KIF22  Approved symbol           KIF22   HGNC:6391
3        DCTN6  Approved symbol           DCTN6  HGNC:16964
4         BET1  Approved symbol            BET1  HGNC:14562
...        ...              ...             ...         ...
13700   MFSD11  Approved symbol          MFSD11  HGNC:25458
13701  SLCO1C1  Approved symbol         SLCO1C1  HGNC:13819
13702  SLC16A2  Approved symbol         SLC16A2  HGNC:10923
13703  RNASE12  Approved symbol         RNASE12  HGNC:24211
13704  RNASE11  Approved symbol         RNASE11  HGNC:19269

[13179 rows x 4 columns]

In [302]:
STRINGdb_features_solucao1['Match type'].value_counts()

Approved symbol    13035
Previous symbol       67
Unmatched             58
Alias symbol          15
Entry withdrawn        4
Name: Match type, dtype: int64

In [303]:
# Salvando a lista final de traduções 

STRINGdb_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_STRINGdb_final2.tsv', sep='\t')

## IREF_2015

In [304]:
sorted_column_IREF_2015_features = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/IREF_2015_features_padrao.tsv', sep='\t', index_col='Unnamed: 0')

IREF_2015_features = sorted_column_IREF_2015_features.rename(columns={"Unnamed: 0.1": "gene"})

IREF_2015_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1BG,0.000000,0.0,0.167401,0.000000,0.000000,0.255263,0.000000,0.095477,0.000000,...,0.012838,0.040970,0.050114,0.000000,0.000000,0.022774,0.028288,0.013054,0.000000,0.007712
1,A1CF,0.000000,0.0,0.000000,0.000000,0.317241,0.000000,0.000000,0.095477,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
2,A2M,0.000000,0.0,0.000000,0.184049,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AADAT,0.670455,0.0,0.000000,0.000000,0.682759,0.000000,0.167742,0.000000,0.000000,...,0.012796,0.000000,0.000000,0.040790,0.000000,0.045023,0.000000,0.012517,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12124,ZXDC,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
12125,ZYG11B,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
12126,ZYX,0.000000,0.0,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
12127,ZZEF1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.833948,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
12128,ZZZ3,0.000000,0.0,0.000000,0.365031,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [305]:
lista_IREF_2015 = IREF_2015_features[['gene']]

lista_IREF_2015

         gene
0        A1BG
1        A1CF
2         A2M
3        AAAS
4       AADAT
...       ...
12124    ZXDC
12125  ZYG11B
12126     ZYX
12127   ZZEF1
12128    ZZZ3

[12129 rows x 1 columns]

In [60]:
lista_IREF_2015.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_2015.tsv', sep='\t', header=False, index=False)

In [306]:
IREF_2015_features_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_2015_trad2.csv', header=1)

IREF_2015_features_trad2 = IREF_2015_features_trad.drop(columns=['Approved name', 'Location'])

IREF_2015_features_trad2

        Input       Match type Approved symbol     HGNC ID
0        A1BG  Approved symbol            A1BG      HGNC:5
1        A1CF  Approved symbol            A1CF  HGNC:24086
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4       AADAT  Approved symbol           AADAT  HGNC:17929
...       ...              ...             ...         ...
12650    ZXDC  Approved symbol            ZXDC  HGNC:28160
12651  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
12652     ZYX  Approved symbol             ZYX  HGNC:13200
12653   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
12654    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[12655 rows x 4 columns]

In [307]:
IREF_2015_features_trad2['Match type'].value_counts()

Approved symbol    11271
Previous symbol      883
Alias symbol         483
Unmatched             17
Entry withdrawn        1
Name: Match type, dtype: int64

In [308]:
IREF_2015_features_solucao1 = IREF_2015_features_trad2.drop_duplicates(subset = ['Input'], keep = 'first')

IREF_2015_features_solucao1

        Input       Match type Approved symbol     HGNC ID
0        A1BG  Approved symbol            A1BG      HGNC:5
1        A1CF  Approved symbol            A1CF  HGNC:24086
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4       AADAT  Approved symbol           AADAT  HGNC:17929
...       ...              ...             ...         ...
12650    ZXDC  Approved symbol            ZXDC  HGNC:28160
12651  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
12652     ZYX  Approved symbol             ZYX  HGNC:13200
12653   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
12654    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[12129 rows x 4 columns]

In [309]:
IREF_2015_features_solucao1['Match type'].value_counts()

Approved symbol    11271
Previous symbol      801
Alias symbol          39
Unmatched             17
Entry withdrawn        1
Name: Match type, dtype: int64

In [310]:
# Salvando a lista final de traduções 

IREF_2015_features_solucao1.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_2015_final2.tsv', sep='\t')

# Substituir os genes traduzidos em cada uma das listas

### MULTINET

In [311]:
# Leitura dos dicionários dos genes

MULTINET_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_MULTINET_final2.tsv', sep='\t', index_col='Unnamed: 0')

MULTINET_genes

        Input       Match type Approved symbol     HGNC ID
0        A1CF  Approved symbol            A1CF  HGNC:24086
1       A2BP1     Alias symbol          RBFOX1  HGNC:18222
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4        AACS  Approved symbol            AACS  HGNC:21298
...       ...              ...             ...         ...
14930    ZXDC  Approved symbol            ZXDC  HGNC:28160
14931  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
14932     ZYX  Approved symbol             ZYX  HGNC:13200
14933   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
14934    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[14398 rows x 4 columns]

In [312]:
# Lista de genes com as features

MULTINET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,A2BP1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
14394,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.000000,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [313]:
# Substituir a coluna gene da lista pela Approved symbol do dicionário

MULTINET_features.replace(MULTINET_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

MULTINET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,RBFOX1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
14394,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.000000,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [314]:
MULTINET = MULTINET_features[MULTINET_features['gene'].notna()]

In [315]:
MULTINET

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,RBFOX1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
14394,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.000000,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [316]:
MULTINET_2 = MULTINET.drop_duplicates(subset = ['gene'], keep = 'first')

MULTINET_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,RBFOX1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14393,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
14394,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.000000,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [317]:
MULTINET_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/MULTINET_features2.tsv', sep='\t')

### CPDB

In [318]:
CPDB_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_CPDB_final2.tsv', sep='\t', index_col='Unnamed: 0')

CPDB_genes

         Input       Match type Approved symbol     HGNC ID
0        STIM1  Approved symbol           STIM1  HGNC:11386
1        TRPC1  Approved symbol           TRPC1  HGNC:12333
2         NOS1  Approved symbol            NOS1   HGNC:7872
4       ATP2B4  Approved symbol          ATP2B4    HGNC:817
5        ABCC9  Approved symbol           ABCC9     HGNC:60
...        ...              ...             ...         ...
14152   GPR153  Approved symbol          GPR153  HGNC:23618
14153      HDC  Approved symbol             HDC   HGNC:4855
14155    CSMD1  Approved symbol           CSMD1  HGNC:14026
14156  BHLHE22  Approved symbol         BHLHE22  HGNC:11963
14157   PROKR1  Approved symbol          PROKR1   HGNC:4524

[13627 rows x 4 columns]

In [319]:
CPDB_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,STIM1,0.000000,0.000000,0.449339,0.000000,0.0,0.428947,0.000000,0.000000,0.000000,...,0.000000,0.040940,0.000000,0.060833,0.000000,0.000000,0.000000,0.012993,0.003601,0.007459
1,TRPC1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040655,0.024799,0.060202,0.054278,0.022758,0.000000,0.000000,0.000000,0.007545
2,NOS1,0.000000,0.000000,0.000000,0.000000,0.0,0.165789,0.000000,0.000000,0.000000,...,0.063345,0.080900,0.048884,0.038974,0.103072,0.022690,0.055677,0.048721,0.000000,0.028677
3,ATP2B4,0.272727,0.000000,0.000000,0.000000,0.0,0.000000,0.148387,0.000000,0.000000,...,0.038215,0.000000,0.074138,0.040063,0.054143,0.045420,0.053870,0.025206,0.007193,0.014863
4,ABCC9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.012769,0.040659,0.024758,0.058909,0.000000,0.045414,0.055910,0.187905,0.010787,0.029335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,GPR153,0.000000,0.000000,0.176211,0.000000,0.0,0.250000,0.212903,0.271357,0.597786,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007677
13623,HDC,0.000000,0.000000,0.308370,0.000000,0.0,0.000000,0.000000,0.175879,0.000000,...,0.000000,0.000000,0.000000,0.040862,0.000000,0.022764,0.000000,0.026045,0.003603,0.007667
13624,CSMD1,0.920455,0.708492,0.000000,0.582822,0.0,0.000000,0.000000,0.000000,0.000000,...,0.062828,0.158012,0.169735,0.332902,0.248689,0.157486,0.108880,0.346369,0.010780,0.046940
13625,BHLHE22,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040962,0.025052,0.000000,0.000000,0.000000,0.000000,0.025961,0.000000,0.003847
13626,PROKR1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.040201,0.000000,...,0.000000,0.000000,0.025006,0.061207,0.000000,0.022764,0.000000,0.038959,0.000000,0.015383

In [320]:
CPDB_features.replace(CPDB_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

CPDB_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,STIM1,0.000000,0.000000,0.449339,0.000000,0.0,0.428947,0.000000,0.000000,0.000000,...,0.000000,0.040940,0.000000,0.060833,0.000000,0.000000,0.000000,0.012993,0.003601,0.007459
1,TRPC1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040655,0.024799,0.060202,0.054278,0.022758,0.000000,0.000000,0.000000,0.007545
2,NOS1,0.000000,0.000000,0.000000,0.000000,0.0,0.165789,0.000000,0.000000,0.000000,...,0.063345,0.080900,0.048884,0.038974,0.103072,0.022690,0.055677,0.048721,0.000000,0.028677
3,ATP2B4,0.272727,0.000000,0.000000,0.000000,0.0,0.000000,0.148387,0.000000,0.000000,...,0.038215,0.000000,0.074138,0.040063,0.054143,0.045420,0.053870,0.025206,0.007193,0.014863
4,ABCC9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.012769,0.040659,0.024758,0.058909,0.000000,0.045414,0.055910,0.187905,0.010787,0.029335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,GPR153,0.000000,0.000000,0.176211,0.000000,0.0,0.250000,0.212903,0.271357,0.597786,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007677
13623,HDC,0.000000,0.000000,0.308370,0.000000,0.0,0.000000,0.000000,0.175879,0.000000,...,0.000000,0.000000,0.000000,0.040862,0.000000,0.022764,0.000000,0.026045,0.003603,0.007667
13624,CSMD1,0.920455,0.708492,0.000000,0.582822,0.0,0.000000,0.000000,0.000000,0.000000,...,0.062828,0.158012,0.169735,0.332902,0.248689,0.157486,0.108880,0.346369,0.010780,0.046940
13625,BHLHE22,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040962,0.025052,0.000000,0.000000,0.000000,0.000000,0.025961,0.000000,0.003847
13626,PROKR1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.040201,0.000000,...,0.000000,0.000000,0.025006,0.061207,0.000000,0.022764,0.000000,0.038959,0.000000,0.015383

In [321]:
CPDB = CPDB_features[CPDB_features['gene'].notna()]

CPDB

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,STIM1,0.000000,0.000000,0.449339,0.000000,0.0,0.428947,0.000000,0.000000,0.000000,...,0.000000,0.040940,0.000000,0.060833,0.000000,0.000000,0.000000,0.012993,0.003601,0.007459
1,TRPC1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040655,0.024799,0.060202,0.054278,0.022758,0.000000,0.000000,0.000000,0.007545
2,NOS1,0.000000,0.000000,0.000000,0.000000,0.0,0.165789,0.000000,0.000000,0.000000,...,0.063345,0.080900,0.048884,0.038974,0.103072,0.022690,0.055677,0.048721,0.000000,0.028677
3,ATP2B4,0.272727,0.000000,0.000000,0.000000,0.0,0.000000,0.148387,0.000000,0.000000,...,0.038215,0.000000,0.074138,0.040063,0.054143,0.045420,0.053870,0.025206,0.007193,0.014863
4,ABCC9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.012769,0.040659,0.024758,0.058909,0.000000,0.045414,0.055910,0.187905,0.010787,0.029335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,GPR153,0.000000,0.000000,0.176211,0.000000,0.0,0.250000,0.212903,0.271357,0.597786,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007677
13623,HDC,0.000000,0.000000,0.308370,0.000000,0.0,0.000000,0.000000,0.175879,0.000000,...,0.000000,0.000000,0.000000,0.040862,0.000000,0.022764,0.000000,0.026045,0.003603,0.007667
13624,CSMD1,0.920455,0.708492,0.000000,0.582822,0.0,0.000000,0.000000,0.000000,0.000000,...,0.062828,0.158012,0.169735,0.332902,0.248689,0.157486,0.108880,0.346369,0.010780,0.046940
13625,BHLHE22,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040962,0.025052,0.000000,0.000000,0.000000,0.000000,0.025961,0.000000,0.003847
13626,PROKR1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.040201,0.000000,...,0.000000,0.000000,0.025006,0.061207,0.000000,0.022764,0.000000,0.038959,0.000000,0.015383

In [322]:
CPDB_2 = CPDB.drop_duplicates(subset = ['gene'], keep = 'first')

CPDB_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,STIM1,0.000000,0.000000,0.449339,0.000000,0.0,0.428947,0.000000,0.000000,0.000000,...,0.000000,0.040940,0.000000,0.060833,0.000000,0.000000,0.000000,0.012993,0.003601,0.007459
1,TRPC1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040655,0.024799,0.060202,0.054278,0.022758,0.000000,0.000000,0.000000,0.007545
2,NOS1,0.000000,0.000000,0.000000,0.000000,0.0,0.165789,0.000000,0.000000,0.000000,...,0.063345,0.080900,0.048884,0.038974,0.103072,0.022690,0.055677,0.048721,0.000000,0.028677
3,ATP2B4,0.272727,0.000000,0.000000,0.000000,0.0,0.000000,0.148387,0.000000,0.000000,...,0.038215,0.000000,0.074138,0.040063,0.054143,0.045420,0.053870,0.025206,0.007193,0.014863
4,ABCC9,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.012769,0.040659,0.024758,0.058909,0.000000,0.045414,0.055910,0.187905,0.010787,0.029335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,GPR153,0.000000,0.000000,0.176211,0.000000,0.0,0.250000,0.212903,0.271357,0.597786,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007677
13623,HDC,0.000000,0.000000,0.308370,0.000000,0.0,0.000000,0.000000,0.175879,0.000000,...,0.000000,0.000000,0.000000,0.040862,0.000000,0.022764,0.000000,0.026045,0.003603,0.007667
13624,CSMD1,0.920455,0.708492,0.000000,0.582822,0.0,0.000000,0.000000,0.000000,0.000000,...,0.062828,0.158012,0.169735,0.332902,0.248689,0.157486,0.108880,0.346369,0.010780,0.046940
13625,BHLHE22,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040962,0.025052,0.000000,0.000000,0.000000,0.000000,0.025961,0.000000,0.003847
13626,PROKR1,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.040201,0.000000,...,0.000000,0.000000,0.025006,0.061207,0.000000,0.022764,0.000000,0.038959,0.000000,0.015383

In [323]:
CPDB_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/CPDB_features2.tsv', sep='\t')

### IREF

In [326]:
# Leitura dos dicionários dos genes

IREF_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_final2.tsv', sep='\t', index_col='Unnamed: 0')

IREF_genes

         Input       Match type Approved symbol     HGNC ID
0         DTX3  Approved symbol            DTX3  HGNC:24457
1       UBE2D4  Approved symbol          UBE2D4  HGNC:21647
2        PROP1  Approved symbol           PROP1   HGNC:9455
3      MAGEA11  Approved symbol         MAGEA11   HGNC:6798
4       TRIM39  Approved symbol          TRIM39  HGNC:10065
...        ...              ...             ...         ...
17606    GSTT2  Approved symbol           GSTT2   HGNC:4642
17607   KCNK17  Approved symbol          KCNK17  HGNC:14465
17608     TGM6  Approved symbol            TGM6  HGNC:16255
17609   IGSF11  Approved symbol          IGSF11  HGNC:16669
17610     TBX3  Approved symbol            TBX3  HGNC:11602

[17013 rows x 4 columns]

In [328]:
# Lista de genes com as features

IREF_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,DTX3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.025035,0.040857,0.000000,0.000000,0.0,0.012973,0.000000,0.000000
1,UBE2D4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022751,0.0,0.000000,0.000000,0.003881
2,PROP1,0.0,0.0,0.0,0.0,0.0,0.000000,0.713978,0.241206,0.0,...,0.000000,0.000000,0.000000,0.020519,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,MAGEA11,0.0,0.0,0.0,0.0,0.0,0.000000,0.079570,0.000000,0.0,...,0.000000,0.000000,0.000000,0.081227,0.000000,0.000000,0.0,0.038889,0.003603,0.011579
4,TRIM39,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.040836,0.000000,0.020380,0.054052,0.000000,0.0,0.012212,0.003598,0.003753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17008,GSTT2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17009,KCNK17,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.012835,0.000000,0.000000,0.040468,0.000000,0.022770,0.0,0.000000,0.000000,0.003856
17010,TGM6,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.025661,0.081913,0.000000,0.000000,0.054257,0.045526,0.0,0.026077,0.000000,0.019106
17011,IGSF11,0.0,0.0,0.0,0.0,0.0,0.000000,0.346237,0.000000,0.0,...,0.012793,0.000000,0.024650,0.039651,0.000000,0.022722,0.0,0.012370,0.000000,0.003582
17012,TBX3,0.0,0.0,0.0,0.0,0.0,0.165789,0.000000,0.000000,0.0,...,0.012827,0.040908,0.024975,0.080053,0.000000,0.091010,0.0,0.050628,0.000000,0.015128

In [329]:
# Substituir a coluna gene da lista pela Approved symbol do dicionário

IREF_features.replace(IREF_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

IREF_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,DTX3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.025035,0.040857,0.000000,0.000000,0.0,0.012973,0.000000,0.000000
1,UBE2D4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022751,0.0,0.000000,0.000000,0.003881
2,PROP1,0.0,0.0,0.0,0.0,0.0,0.000000,0.713978,0.241206,0.0,...,0.000000,0.000000,0.000000,0.020519,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,MAGEA11,0.0,0.0,0.0,0.0,0.0,0.000000,0.079570,0.000000,0.0,...,0.000000,0.000000,0.000000,0.081227,0.000000,0.000000,0.0,0.038889,0.003603,0.011579
4,TRIM39,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.040836,0.000000,0.020380,0.054052,0.000000,0.0,0.012212,0.003598,0.003753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17008,GSTT2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17009,KCNK17,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.012835,0.000000,0.000000,0.040468,0.000000,0.022770,0.0,0.000000,0.000000,0.003856
17010,TGM6,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.025661,0.081913,0.000000,0.000000,0.054257,0.045526,0.0,0.026077,0.000000,0.019106
17011,IGSF11,0.0,0.0,0.0,0.0,0.0,0.000000,0.346237,0.000000,0.0,...,0.012793,0.000000,0.024650,0.039651,0.000000,0.022722,0.0,0.012370,0.000000,0.003582
17012,TBX3,0.0,0.0,0.0,0.0,0.0,0.165789,0.000000,0.000000,0.0,...,0.012827,0.040908,0.024975,0.080053,0.000000,0.091010,0.0,0.050628,0.000000,0.015128

In [330]:
IREF = IREF_features[IREF_features['gene'].notna()]

IREF

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,DTX3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.025035,0.040857,0.000000,0.000000,0.0,0.012973,0.000000,0.000000
1,UBE2D4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022751,0.0,0.000000,0.000000,0.003881
2,PROP1,0.0,0.0,0.0,0.0,0.0,0.000000,0.713978,0.241206,0.0,...,0.000000,0.000000,0.000000,0.020519,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,MAGEA11,0.0,0.0,0.0,0.0,0.0,0.000000,0.079570,0.000000,0.0,...,0.000000,0.000000,0.000000,0.081227,0.000000,0.000000,0.0,0.038889,0.003603,0.011579
4,TRIM39,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.040836,0.000000,0.020380,0.054052,0.000000,0.0,0.012212,0.003598,0.003753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17008,GSTT2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17009,KCNK17,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.012835,0.000000,0.000000,0.040468,0.000000,0.022770,0.0,0.000000,0.000000,0.003856
17010,TGM6,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.025661,0.081913,0.000000,0.000000,0.054257,0.045526,0.0,0.026077,0.000000,0.019106
17011,IGSF11,0.0,0.0,0.0,0.0,0.0,0.000000,0.346237,0.000000,0.0,...,0.012793,0.000000,0.024650,0.039651,0.000000,0.022722,0.0,0.012370,0.000000,0.003582
17012,TBX3,0.0,0.0,0.0,0.0,0.0,0.165789,0.000000,0.000000,0.0,...,0.012827,0.040908,0.024975,0.080053,0.000000,0.091010,0.0,0.050628,0.000000,0.015128

In [331]:
IREF_2 = IREF.drop_duplicates(subset = ['gene'], keep = 'first')

IREF_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,DTX3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.025035,0.040857,0.000000,0.000000,0.0,0.012973,0.000000,0.000000
1,UBE2D4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.022751,0.0,0.000000,0.000000,0.003881
2,PROP1,0.0,0.0,0.0,0.0,0.0,0.000000,0.713978,0.241206,0.0,...,0.000000,0.000000,0.000000,0.020519,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,MAGEA11,0.0,0.0,0.0,0.0,0.0,0.000000,0.079570,0.000000,0.0,...,0.000000,0.000000,0.000000,0.081227,0.000000,0.000000,0.0,0.038889,0.003603,0.011579
4,TRIM39,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.040836,0.000000,0.020380,0.054052,0.000000,0.0,0.012212,0.003598,0.003753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17008,GSTT2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
17009,KCNK17,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.012835,0.000000,0.000000,0.040468,0.000000,0.022770,0.0,0.000000,0.000000,0.003856
17010,TGM6,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.025661,0.081913,0.000000,0.000000,0.054257,0.045526,0.0,0.026077,0.000000,0.019106
17011,IGSF11,0.0,0.0,0.0,0.0,0.0,0.000000,0.346237,0.000000,0.0,...,0.012793,0.000000,0.024650,0.039651,0.000000,0.022722,0.0,0.012370,0.000000,0.003582
17012,TBX3,0.0,0.0,0.0,0.0,0.0,0.165789,0.000000,0.000000,0.0,...,0.012827,0.040908,0.024975,0.080053,0.000000,0.091010,0.0,0.050628,0.000000,0.015128

In [332]:
IREF_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/IREF_features2.tsv', sep='\t')

### PCNET

In [190]:
# Leitura dos dicionários dos genes

PCNET_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_PCNET_final2.tsv', sep='\t', index_col='Unnamed: 0')

PCNET_genes

         Input       Match type Approved symbol     HGNC ID
0       UBE2Q1  Approved symbol          UBE2Q1  HGNC:15698
1        RNF14  Approved symbol           RNF14  HGNC:10058
2       UBE2Q2  Approved symbol          UBE2Q2  HGNC:19248
3        TMCO1  Approved symbol           TMCO1  HGNC:18188
4        UBAC1  Approved symbol           UBAC1  HGNC:30221
...        ...              ...             ...         ...
20421    BAGE4  Approved symbol           BAGE4  HGNC:15730
20422  FAM181B  Approved symbol         FAM181B  HGNC:28512
20423    IGFL3  Approved symbol           IGFL3  HGNC:32930
20424     BAT4  Previous symbol          GPANK1  HGNC:13920
20425   TPT1P8  Approved symbol          TPT1P8  HGNC:24088

[19779 rows x 4 columns]

In [191]:
PCNET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,UBE2Q1,0.0,0.000000,0.696035,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.012837,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012896,0.000000,0.011571
1,RNF14,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.241206,0.000000,...,0.025470,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012068,0.007107,0.007325
2,UBE2Q2,0.0,0.000000,0.334802,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013017,0.003560,0.003769
3,TMCO1,0.0,0.000000,0.000000,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.003732
4,UBAC1,0.0,0.376426,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.439114,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013057,0.000000,0.011592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19776,BAGE4,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19777,FAM181B,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.061346,0.0,0.0,0.00000,0.013027,0.000000,0.000000
19778,IGFL3,0.0,0.000000,0.167401,0.0,0.000000,0.0,0.000000,0.095477,0.000000,...,0.000000,0.081971,0.0,0.000000,0.0,0.0,0.02843,0.013023,0.000000,0.000000
19779,BAT4,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19780,TPT1P8,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000

In [192]:
# Substituir a coluna gene da lista pela Approved symbol do dicionário

PCNET_features.replace(PCNET_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

PCNET_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,UBE2Q1,0.0,0.000000,0.696035,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.012837,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012896,0.000000,0.011571
1,RNF14,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.241206,0.000000,...,0.025470,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012068,0.007107,0.007325
2,UBE2Q2,0.0,0.000000,0.334802,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013017,0.003560,0.003769
3,TMCO1,0.0,0.000000,0.000000,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.003732
4,UBAC1,0.0,0.376426,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.439114,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013057,0.000000,0.011592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19776,BAGE4,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19777,FAM181B,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.061346,0.0,0.0,0.00000,0.013027,0.000000,0.000000
19778,IGFL3,0.0,0.000000,0.167401,0.0,0.000000,0.0,0.000000,0.095477,0.000000,...,0.000000,0.081971,0.0,0.000000,0.0,0.0,0.02843,0.013023,0.000000,0.000000
19779,GPANK1,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19780,TPT1P8,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000

In [222]:
dataframe1 = PCNET_features

In [193]:
PCNET = PCNET_features[PCNET_features['gene'].notna()]

PCNET_2 = PCNET.drop_duplicates(subset = ['gene'], keep = 'first')

PCNET_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,UBE2Q1,0.000000,0.000000,0.696035,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.012837,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012896,0.000000,0.011571
1,RNF14,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.241206,0.000000,...,0.025470,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.012068,0.007107,0.007325
2,UBE2Q2,0.000000,0.000000,0.334802,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013017,0.003560,0.003769
3,TMCO1,0.000000,0.000000,0.000000,0.0,0.641379,0.0,0.133333,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.003732
4,UBAC1,0.000000,0.376426,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.439114,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.013057,0.000000,0.011592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19775,CD300LD,0.734848,0.000000,0.000000,0.0,0.000000,0.0,0.000000,1.000000,0.000000,...,0.012842,0.122938,0.0,0.061632,0.0,0.0,0.00000,0.052157,0.000000,0.000000
19776,BAGE4,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000
19777,FAM181B,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.061346,0.0,0.0,0.00000,0.013027,0.000000,0.000000
19778,IGFL3,0.000000,0.000000,0.167401,0.0,0.000000,0.0,0.000000,0.095477,0.000000,...,0.000000,0.081971,0.0,0.000000,0.0,0.0,0.02843,0.013023,0.000000,0.000000
19780,TPT1P8,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.000000

In [224]:
print(PCNET_2.loc[lista_PCNET['gene'] == 'FAM71C'])

        gene  CNA: BLCA  CNA: BRCA  CNA: CESC  CNA: COAD  CNA: ESCA  \
9051  GARIN6        0.0   0.254753        0.0        0.0   0.358621

      CNA: HNSC  CNA: KIRC  CNA: KIRP  CNA: LIHC  ...  MF: KIRC  MF: KIRP  \
9051   0.163212        0.0        0.0        0.0  ...  0.012837  0.040981

      MF: LIHC  MF: LUAD  MF: LUSC  MF: PRAD  MF: READ  MF: STAD  MF: THCA  \
9051  0.025048  0.041103       0.0  0.022776       0.0  0.026085  0.003604

      MF: UCEC
9051  0.007735

[1 rows x 65 columns]

In [194]:
PCNET_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/PCNET_features2.tsv', sep='\t')

### STRINGdb

In [335]:
# Leitura dos dicionários dos genes

STRINGdb_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_STRINGdb_final2.tsv', sep='\t', index_col='Unnamed: 0')

STRINGdb_genes

         Input       Match type Approved symbol     HGNC ID
0         ARF5  Approved symbol            ARF5    HGNC:658
1       SPTBN2  Approved symbol          SPTBN2  HGNC:11276
2        KIF22  Approved symbol           KIF22   HGNC:6391
3        DCTN6  Approved symbol           DCTN6  HGNC:16964
4         BET1  Approved symbol            BET1  HGNC:14562
...        ...              ...             ...         ...
13700   MFSD11  Approved symbol          MFSD11  HGNC:25458
13701  SLCO1C1  Approved symbol         SLCO1C1  HGNC:13819
13702  SLC16A2  Approved symbol         SLC16A2  HGNC:10923
13703  RNASE12  Approved symbol         RNASE12  HGNC:24211
13704  RNASE11  Approved symbol         RNASE11  HGNC:19269

[13179 rows x 4 columns]

In [336]:
STRINGdb_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,ARF5,0.000000,0.0,0.264317,0.0,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.000000,0.040985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011607
1,SPTBN2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012766,0.081138,0.048677,0.039826,0.053086,0.021047,0.025923,0.035777,0.007194,0.060659
2,KIF22,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012803,0.000000,0.000000,0.020363,0.000000,0.022747,0.000000,0.000000,0.000000,0.000000
3,DCTN6,0.954545,0.0,0.000000,0.0,0.517241,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013015,0.000000,0.003847
4,BET1,0.000000,0.0,0.000000,0.0,0.786207,0.444737,0.000000,0.000000,0.000000,...,0.000000,0.040930,0.050092,0.000000,0.000000,0.022755,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174,MFSD11,0.734848,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.081267,0.024685,0.000000,0.053600,0.000000,0.000000,0.013008,0.000000,0.007231
13175,SLCO1C1,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.038355,0.040815,0.024792,0.039038,0.162867,0.045482,0.000000,0.051008,0.000000,0.014983
13176,SLC16A2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012828,0.000000,0.000000,0.000000,0.054732,0.045522,0.028346,0.000000,0.000000,0.023163
13177,RNASE12,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013037,0.000000,0.000000
13178,RNASE11,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012824,0.000000,0.000000,0.000000,0.109436,0.000000,0.000000,0.012947,0.000000,0.007638

In [337]:
# Substituir a coluna gene da lista pela Approved symbol do dicionário

STRINGdb_features.replace(STRINGdb_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

STRINGdb_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,ARF5,0.000000,0.0,0.264317,0.0,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.000000,0.040985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011607
1,SPTBN2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012766,0.081138,0.048677,0.039826,0.053086,0.021047,0.025923,0.035777,0.007194,0.060659
2,KIF22,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012803,0.000000,0.000000,0.020363,0.000000,0.022747,0.000000,0.000000,0.000000,0.000000
3,DCTN6,0.954545,0.0,0.000000,0.0,0.517241,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013015,0.000000,0.003847
4,BET1,0.000000,0.0,0.000000,0.0,0.786207,0.444737,0.000000,0.000000,0.000000,...,0.000000,0.040930,0.050092,0.000000,0.000000,0.022755,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174,MFSD11,0.734848,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.081267,0.024685,0.000000,0.053600,0.000000,0.000000,0.013008,0.000000,0.007231
13175,SLCO1C1,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.038355,0.040815,0.024792,0.039038,0.162867,0.045482,0.000000,0.051008,0.000000,0.014983
13176,SLC16A2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012828,0.000000,0.000000,0.000000,0.054732,0.045522,0.028346,0.000000,0.000000,0.023163
13177,RNASE12,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013037,0.000000,0.000000
13178,RNASE11,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012824,0.000000,0.000000,0.000000,0.109436,0.000000,0.000000,0.012947,0.000000,0.007638

In [338]:
# Remove as traduções que não tinham resultado (Unmatched) e remove as duplicadas de casos que diferentes genes traduziram para um mesmo

STRINGdb = STRINGdb_features[STRINGdb_features['gene'].notna()]

STRINGdb_2 = STRINGdb.drop_duplicates(subset = ['gene'], keep = 'first')

STRINGdb_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,ARF5,0.000000,0.0,0.264317,0.0,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.000000,0.040985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011607
1,SPTBN2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012766,0.081138,0.048677,0.039826,0.053086,0.021047,0.025923,0.035777,0.007194,0.060659
2,KIF22,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012803,0.000000,0.000000,0.020363,0.000000,0.022747,0.000000,0.000000,0.000000,0.000000
3,DCTN6,0.954545,0.0,0.000000,0.0,0.517241,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013015,0.000000,0.003847
4,BET1,0.000000,0.0,0.000000,0.0,0.786207,0.444737,0.000000,0.000000,0.000000,...,0.000000,0.040930,0.050092,0.000000,0.000000,0.022755,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13174,MFSD11,0.734848,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.081267,0.024685,0.000000,0.053600,0.000000,0.000000,0.013008,0.000000,0.007231
13175,SLCO1C1,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.038355,0.040815,0.024792,0.039038,0.162867,0.045482,0.000000,0.051008,0.000000,0.014983
13176,SLC16A2,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012828,0.000000,0.000000,0.000000,0.054732,0.045522,0.028346,0.000000,0.000000,0.023163
13177,RNASE12,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013037,0.000000,0.000000
13178,RNASE11,0.000000,0.0,0.000000,0.0,0.000000,0.197368,0.000000,0.276382,0.000000,...,0.012824,0.000000,0.000000,0.000000,0.109436,0.000000,0.000000,0.012947,0.000000,0.007638

In [339]:
STRINGdb_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/STRINGdb_features2.tsv', sep='\t')

### IREF_2015

In [340]:
# Leitura dos dicionários dos genes

IREF_2015_genes = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_IREF_2015_final2.tsv', sep='\t', index_col='Unnamed: 0')

IREF_2015_genes

        Input       Match type Approved symbol     HGNC ID
0        A1BG  Approved symbol            A1BG      HGNC:5
1        A1CF  Approved symbol            A1CF  HGNC:24086
2         A2M  Approved symbol             A2M      HGNC:7
3        AAAS  Approved symbol            AAAS  HGNC:13666
4       AADAT  Approved symbol           AADAT  HGNC:17929
...       ...              ...             ...         ...
12650    ZXDC  Approved symbol            ZXDC  HGNC:28160
12651  ZYG11B  Approved symbol          ZYG11B  HGNC:25820
12652     ZYX  Approved symbol             ZYX  HGNC:13200
12653   ZZEF1  Approved symbol           ZZEF1  HGNC:29027
12654    ZZZ3  Approved symbol            ZZZ3  HGNC:24523

[12129 rows x 4 columns]

In [341]:
IREF_2015_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1BG,0.000000,0.0,0.167401,0.000000,0.000000,0.255263,0.000000,0.095477,0.000000,...,0.012838,0.040970,0.050114,0.000000,0.000000,0.022774,0.028288,0.013054,0.000000,0.007712
1,A1CF,0.000000,0.0,0.000000,0.000000,0.317241,0.000000,0.000000,0.095477,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
2,A2M,0.000000,0.0,0.000000,0.184049,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AADAT,0.670455,0.0,0.000000,0.000000,0.682759,0.000000,0.167742,0.000000,0.000000,...,0.012796,0.000000,0.000000,0.040790,0.000000,0.045023,0.000000,0.012517,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12124,ZXDC,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
12125,ZYG11B,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
12126,ZYX,0.000000,0.0,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
12127,ZZEF1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.833948,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
12128,ZZZ3,0.000000,0.0,0.000000,0.365031,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [342]:
# Substituir a coluna gene da lista pela Approved symbol do dicionário

IREF_2015_features.replace(IREF_2015_genes.set_index('Input').to_dict()['Approved symbol'], inplace = True)

IREF_2015_features

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1BG,0.000000,0.0,0.167401,0.000000,0.000000,0.255263,0.000000,0.095477,0.000000,...,0.012838,0.040970,0.050114,0.000000,0.000000,0.022774,0.028288,0.013054,0.000000,0.007712
1,A1CF,0.000000,0.0,0.000000,0.000000,0.317241,0.000000,0.000000,0.095477,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
2,A2M,0.000000,0.0,0.000000,0.184049,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AADAT,0.670455,0.0,0.000000,0.000000,0.682759,0.000000,0.167742,0.000000,0.000000,...,0.012796,0.000000,0.000000,0.040790,0.000000,0.045023,0.000000,0.012517,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12124,ZXDC,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
12125,ZYG11B,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
12126,ZYX,0.000000,0.0,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
12127,ZZEF1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.833948,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
12128,ZZZ3,0.000000,0.0,0.000000,0.365031,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [343]:
# Remove as traduções que não tinham resultado (Unmatched) e remove as duplicadas de casos que diferentes genes traduziram para um mesmo

IREF_2015 = IREF_2015_features[IREF_2015_features['gene'].notna()]

IREF_2015_2 = IREF_2015.drop_duplicates(subset = ['gene'], keep = 'first')

IREF_2015_2

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1BG,0.000000,0.0,0.167401,0.000000,0.000000,0.255263,0.000000,0.095477,0.000000,...,0.012838,0.040970,0.050114,0.000000,0.000000,0.022774,0.028288,0.013054,0.000000,0.007712
1,A1CF,0.000000,0.0,0.000000,0.000000,0.317241,0.000000,0.000000,0.095477,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
2,A2M,0.000000,0.0,0.000000,0.184049,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AADAT,0.670455,0.0,0.000000,0.000000,0.682759,0.000000,0.167742,0.000000,0.000000,...,0.012796,0.000000,0.000000,0.040790,0.000000,0.045023,0.000000,0.012517,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12124,ZXDC,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
12125,ZYG11B,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
12126,ZYX,0.000000,0.0,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
12127,ZZEF1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.833948,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
12128,ZZZ3,0.000000,0.0,0.000000,0.365031,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [344]:
IREF_2015_2.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/IREF_2015_features2.tsv', sep='\t')

## União das redes

In [3]:
MULTINET = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/MULTINET_features2.tsv', sep='\t', index_col='Unnamed: 0')

CPDB = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/CPDB_features2.tsv', sep='\t', index_col='Unnamed: 0')

IREF = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/IREF_features2.tsv', sep='\t', index_col='Unnamed: 0')

PCNET = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/PCNET_features2.tsv', sep='\t', index_col='Unnamed: 0')

STRINGdb = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/STRINGdb_features2.tsv', sep='\t', index_col='Unnamed: 0')

IREF_2015 = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/IREF_2015_features2.tsv', sep='\t', index_col='Unnamed: 0')

In [11]:
print(PCNET.loc[PCNET['gene'] == 'C19orf12'])

           gene  CNA: BLCA  CNA: BRCA  CNA: CESC  CNA: COAD  CNA: ESCA  \
18982  C19orf12        0.0        0.0        0.0        0.0        0.0

       CNA: HNSC  CNA: KIRC  CNA: KIRP  CNA: LIHC  ...  MF: KIRC  MF: KIRP  \
18982        0.0        0.0        0.0        0.0  ...       0.0       0.0

       MF: LIHC  MF: LUAD  MF: LUSC  MF: PRAD  MF: READ  MF: STAD  MF: THCA  \
18982       0.0       0.0       0.0       0.0       0.0       0.0       0.0

       MF: UCEC
18982       0.0

[1 rows x 65 columns]

In [347]:
teste_todas_redes = pd.concat([MULTINET, CPDB, IREF, PCNET, STRINGdb, IREF_2015])

teste_todas_redes

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,RBFOX1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12124,ZXDC,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.346237,0.000000,0.000000,...,0.000000,0.040907,0.000000,0.000000,0.000000,0.000000,0.000000,0.025721,0.003603,0.011466
12125,ZYG11B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
12126,ZYX,0.0,0.000000,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.125461,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
12127,ZZEF1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.833948,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
12128,ZZZ3,0.0,0.000000,0.000000,0.365031,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [348]:
teste = teste_todas_redes.drop_duplicates(subset = ['gene'], keep = 'first')

teste

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
0,A1CF,0.0,0.000000,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
1,RBFOX1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,A2M,0.0,0.000000,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
3,AAAS,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025661,0.040872,0.000000,0.000000,0.000000,0.000000,0.000000,0.012746,0.003604,0.003829
4,AACS,0.0,0.227126,0.000000,0.000000,0.000000,0.159091,0.000000,0.000000,0.175074,...,0.000000,0.000000,0.000000,0.020504,0.000000,0.000000,0.028397,0.038616,0.003602,0.011557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13167,C1orf167,0.0,0.000000,0.176211,0.000000,0.000000,0.250000,0.212903,0.271357,0.000000,...,0.000000,0.000000,0.025064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003806
13168,C7orf77,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13171,MTRNR2L3,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2873,DMRTC1B,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7937,PNMA6B,0.0,0.000000,0.000000,0.000000,0.000000,0.394737,0.079570,0.000000,0.321033,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [349]:
print(teste.loc[teste['gene'] == 'GARIN5B'])

         gene  CNA: BLCA  CNA: BRCA  CNA: CESC  CNA: COAD  CNA: ESCA  \
5431  GARIN5B   0.587121   0.348542   0.167401        0.0        0.0

      CNA: HNSC  CNA: KIRC  CNA: KIRP  CNA: LIHC  ...  MF: KIRC  MF: KIRP  \
5431        0.0        0.0   0.095477        0.0  ...  0.012834       0.0

      MF: LIHC  MF: LUAD  MF: LUSC  MF: PRAD  MF: READ  MF: STAD  MF: THCA  \
5431       0.0       0.0       0.0       0.0       0.0       0.0       0.0

      MF: UCEC
5431  0.003824

[1 rows x 65 columns]

In [360]:
teste_ord = teste.sort_values('gene')

teste_ord

,gene,CNA: BLCA,CNA: BRCA,CNA: CESC,CNA: COAD,CNA: ESCA,CNA: HNSC,CNA: KIRC,CNA: KIRP,CNA: LIHC,...,MF: KIRC,MF: KIRP,MF: LIHC,MF: LUAD,MF: LUSC,MF: PRAD,MF: READ,MF: STAD,MF: THCA,MF: UCEC
3171,A1BG,0.0,0.0,0.167401,0.000000,0.000000,0.255263,0.000000,0.095477,0.000000,...,0.012838,0.040970,0.050114,0.000000,0.000000,0.022774,0.028288,0.013054,0.000000,0.007712
0,A1CF,0.0,0.0,0.000000,0.000000,0.283951,0.000000,0.000000,0.082251,0.000000,...,0.012698,0.000000,0.024672,0.117901,0.000000,0.090341,0.027762,0.011448,0.000000,0.010251
2,A2M,0.0,0.0,0.000000,0.174419,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012836,0.040877,0.000000,0.122328,0.109769,0.022773,0.000000,0.038998,0.003601,0.019196
13307,A2ML1,0.0,0.0,0.000000,0.184049,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.040866,0.049805,0.040017,0.054533,0.022713,0.000000,0.063755,0.000000,0.007600
19556,A3GALT2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013021,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14664,ZYG11A,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007645
14394,ZYG11B,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012818,0.081662,0.025013,0.000000,0.000000,0.000000,0.000000,0.038673,0.000000,0.000000
14395,ZYX,0.0,0.0,0.264317,0.000000,0.000000,0.000000,0.376344,0.000000,0.100890,...,0.012815,0.000000,0.000000,0.020495,0.000000,0.000000,0.000000,0.012873,0.000000,0.022981
14396,ZZEF1,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.670623,...,0.038417,0.204110,0.000000,0.059756,0.000000,0.068216,0.028239,0.050702,0.003603,0.041296
14397,ZZZ3,0.0,0.0,0.000000,0.345930,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012822,0.000000,0.000000,0.020198,0.000000,0.000000,0.000000,0.000000,0.003603,0.003874

In [361]:
teste_ord.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/features/unity_features.tsv', sep='\t')

In [351]:
lista_teste = teste[['gene']]

lista_teste

           gene
0          A1CF
1        RBFOX1
2           A2M
3          AAAS
4          AACS
...         ...
13167  C1orf167
13168   C7orf77
13171  MTRNR2L3
2873    DMRTC1B
7937     PNMA6B

[19666 rows x 1 columns]

In [352]:
lista_teste.to_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_teste.tsv', sep='\t', header=False, index=False)

In [353]:
lista_trad = pd.read_csv('C:/Users/renan/Desktop/UFRGS/GNN/data/traducao_genes/lista_teste_trad.csv', header=1)

lista_trad

,Input,Match type,Approved symbol,Approved name,HGNC ID,Location
0,A1CF,Approved symbol,A1CF,APOBEC1 complementation factor,HGNC:24086,10q11.23
1,RBFOX1,Approved symbol,RBFOX1,RNA binding fox-1 homolog 1,HGNC:18222,16p13.3
2,A2M,Approved symbol,A2M,alpha-2-macroglobulin,HGNC:7,12p13.31
3,AAAS,Approved symbol,AAAS,aladin WD repeat nucleoporin,HGNC:13666,12q13.13
4,AACS,Approved symbol,AACS,acetoacetyl-CoA synthetase,HGNC:21298,12q24.31
...,...,...,...,...,...,...
20290,C1orf167,Approved symbol,C1orf167,chromosome 1 open reading frame 167,HGNC:25262,1p36.22
20291,C7orf77,Approved symbol,C7orf77,chromosome 7 open reading frame 77,HGNC:51256,7q31.33
20292,MTRNR2L3,Approved symbol,MTRNR2L3,MT-RNR2 like 3 (pseudogene),HGNC:37157,20q13.31
20293,DMRTC1B,Approved symbol,DMRTC1B,DMRT like family C1B,HGNC:31686,Xq13.1
20294,PNMA6B,Approved symbol,PNMA6B,PNMA family member 6B (pseudogene),HGNC:26681,Xq28

In [354]:
lista_trad['Match type'].value_counts()

Approved symbol    19647
Alias symbol         517
Previous symbol      112
Entry withdrawn       19
Name: Match type, dtype: int64

In [355]:
lista_trad2 = lista_trad.drop_duplicates(subset = ['Input'], keep = 'first')

lista_trad2

,Input,Match type,Approved symbol,Approved name,HGNC ID,Location
0,A1CF,Approved symbol,A1CF,APOBEC1 complementation factor,HGNC:24086,10q11.23
1,RBFOX1,Approved symbol,RBFOX1,RNA binding fox-1 homolog 1,HGNC:18222,16p13.3
2,A2M,Approved symbol,A2M,alpha-2-macroglobulin,HGNC:7,12p13.31
3,AAAS,Approved symbol,AAAS,aladin WD repeat nucleoporin,HGNC:13666,12q13.13
4,AACS,Approved symbol,AACS,acetoacetyl-CoA synthetase,HGNC:21298,12q24.31
...,...,...,...,...,...,...
20290,C1orf167,Approved symbol,C1orf167,chromosome 1 open reading frame 167,HGNC:25262,1p36.22
20291,C7orf77,Approved symbol,C7orf77,chromosome 7 open reading frame 77,HGNC:51256,7q31.33
20292,MTRNR2L3,Approved symbol,MTRNR2L3,MT-RNR2 like 3 (pseudogene),HGNC:37157,20q13.31
20293,DMRTC1B,Approved symbol,DMRTC1B,DMRT like family C1B,HGNC:31686,Xq13.1
20294,PNMA6B,Approved symbol,PNMA6B,PNMA family member 6B (pseudogene),HGNC:26681,Xq28

In [356]:
lista_trad2['Match type'].value_counts()

Approved symbol    19647
Entry withdrawn       19
Name: Match type, dtype: int64

In [357]:
lista_trad3 = lista_trad2.rename(columns={"Match type": "match_type"})

lista_trad4 = lista_trad3[lista_trad3.match_type == 'Entry withdrawn']

lista_trad4

,Input,match_type,Approved symbol,Approved name,HGNC ID,Location
1389,C14orf181,Entry withdrawn,C14orf181,NaN,HGNC:33794,NaN
2856,COP,Entry withdrawn,COP,NaN,HGNC:2229,NaN
2882,CORD1,Entry withdrawn,CORD1,NaN,HGNC:2245,NaN
2986,CRIPAK,Entry withdrawn,CRIPAK,NaN,HGNC:26619,NaN
3084,CTD,Entry withdrawn,CTD,NaN,HGNC:2497,NaN
4087,EPR1,Entry withdrawn,EPR1,NaN,HGNC:3417,NaN
4536,FCP1,Entry withdrawn,FCP1,NaN,HGNC:3627,NaN
5636,HIST2H3B,Entry withdrawn,HIST2H3B,NaN,HGNC:20504,NaN
10560,RNU86,Entry withdrawn,RNU86,NaN,HGNC:17130,NaN
13111,TRNAG1,Entry withdrawn,TRNAG1,NaN,HGNC:12272,NaN
14881,U2AF1L5,Entry withdrawn,U2AF1L5,NaN,HGNC:51830,NaN
16155,CBSL,Entry withdrawn,CBSL,NaN,HGNC:51829,NaN
17281,SIK1B,Entry withdrawn,SIK1B,NaN,HGNC:52389,NaN
17657,CRYAA2,Entry withdrawn,CRYAA2,NaN,HGNC:51901,NaN
18247,SMIM11B,Entry withdrawn,SMIM11B,NaN,HGNC:51846,NaN
18438,TMEM155,Entry withdrawn,TMEM155,NaN,HGNC:26418,NaN
19205,SPHAR,Entry withdrawn,SPHAR,NaN,HGNC:16957,NaN
19213,OCLM,Entry withdrawn,OCLM,NaN,HGNC:8103,NaN
20272,GATD3B,Entry withdrawn,GATD3B,NaN,HGNC:53816,NaN

In [25]:
print(teste.loc[teste['gene'] == 'C8orf4'])

         gene  CNA: BLCA  CNA: BRCA  CNA: CESC  CNA: COAD  CNA: ESCA  \
15332  C8orf4        0.0        0.0        0.0        0.0   0.517241

       CNA: HNSC  CNA: KIRC  CNA: KIRP  CNA: LIHC  ...  MF: KIRC  MF: KIRP  \
15332        0.0        0.0        0.0        0.0  ...       0.0       0.0

       MF: LIHC  MF: LUAD  MF: LUSC  MF: PRAD  MF: READ  MF: STAD  MF: THCA  \
15332       0.0       0.0       0.0       0.0       0.0       0.0       0.0

       MF: UCEC
15332       0.0

[1 rows x 65 columns]